### PR TITLE
Added space between 'output' and 'day'

### PR DESCRIPTION
**Pull request by Conseils**
Minor edit - Improve formatting of temperature on scrolling display

### CODE REVIEW

**Comment by alexellis** [comment]
@Conseils  Sounds fair. What was the text printed before/after btw?

**Comment by Conseils** [comment]
Hi,
 Before
Location: LEEDS, GB
Tue: Rain - L: 54F - H: 64FWed: Mostly Cloudy - L: 51F - H: 65F

After
Location: LEEDS, GB
Tue: Rain - L: 54F - H: 64F Wed: Mostly Cloudy - L: 51F - H: 65F

Difference is between is  '64FWed:' to  '64F Wed:'

**Comment by Conseils** [comment]
For UK users here is the code for temperatures in °C

import time
import scrollphat
import socket
import sys
import requests
import json
import urllib

# requires: netifaces for looking up IP in readable way
# requires: requests human readable HTTP requests

def get_location():
    res = requests.get('http://ipinfo.io')
    if(res.status_code == 200):
        json_data = json.loads(res.text)
        return json_data
    return {}

# Python 2 vs 3 breaking changes.
def encode(qs):
    val = ""
    try:
        val = urllib.urlencode(qs).replace("+","%20")
    except:
        val = urllib.parse.urlencode(qs).replace("+", "%20")
    return val

def get_weather(address):
    base = "https://query.yahooapis.com/v1/public/yql?"
    query = "select * from weather.forecast where woeid in (select woeid from geo.places(1) where text=\""+address+"\") and u='c'"
    qs={"q": query, "format": "json", "env": "store://datatables.org/alltableswithkeys"}

    uri = base + encode(qs)                                        

    res = requests.get(uri)
    if(res.status_code==200):
        json_data = json.loads(res.text)
        return json_data
    return {}

def scroll_message(output):
    scrollphat.write_string(output)
    scrollphat.update()

    while(True):
        try:
            scrollphat.scroll()
            scrollphat.update()
            time.sleep(0.2)
        except KeyboardInterrupt:
            return

if(__name__ == '__main__'):
    scrollphat.set_brightness(99) 
    location = get_location()
    location_string = location["city"] +", " + location["country"]
    location_string = "LEEDS, GB"
    print("Location: " + location_string)

    if(location["city"] != None):
        weather = get_weather(location_string)
        output = ""

        # Feel free to pick out other data here, for the scrolling message
        for x in range(0, 2):
            item = weather["query"]["results"]["channel"]["item"]["forecast"][x]
            output = output + " " + item["day"] +": " + item["text"] + " - L: "+ item["low"] + "C - H: "+ item["high"]+"C"

        print(output)
        scroll_message(output)

        scrollphat.clear()

**Comment by alexellis** [comment]
So Fahrenheit didn't mean much to me when I created this example, but it was there for free so I kept it in. We could have an argument of C or F rather than hard-coding C into the code.

Also: `location["country"]` may give you enough to pick between C and F? Pretty sure the endpoint returns in Fahrenheit so we could so if you're formatting in C then just convert with the standard formula. 

@Conseils  thoughts?

**Comment by Conseils** [comment]
Hi,
 sounds cool. I haven't used Fahrenheit since childhood. 
I posted a tested °C version with previous text comments.

To quote Wikipedia.. 

"_By the end of the 20th century, Fahrenheit was only used as the official temperature scale in the United States (including its unincorporated territories), its freely associated states in the Western Pacific (Palau, the Federated States of Micronesia and the Marshall Islands), the Bahamas, Belize, and the Cayman Islands. All other countries in the world now use the Celsius scale, defined since 1954 by absolute zero being −273.15 °C and the triple point of water being at 0.01 °C.[3]_"

So no one really ;-) , perhaps default to C and if US locale switch to F

**Pull request merged**
