### PR TITLE
Enable unit testing/development off-device. And update to IP to show public/private address

### PR DESCRIPTION
**Pull request by alexellis**
I think this is going to be a useful addition to the 'IP' example to give public or private IP address. Could be great as a start-up script when on a public wi-fi hotspot.

### CODE REVIEW

**Comment by alexellisadp** [comment]
I was just going off what I've seen elsewhere but I will remove the comment - no object to the alteration to the IP example though? 

Can I update this PR or do I need to delete it first?

**Comment by alexellis** [comment]
I was just going off what I've seen elsewhere but I will remove the comment - no object to the alteration to the IP example though? 

Can I update this PR or do I need to delete it first?

https://github.com/alexellis/scroll-phat/commit/0a4684627045ba44cc82fb8f4cd8ab54f7be765b

**Comment by alexellis** [comment]
@AndiCui How are we doing on this? The change you asked for has been pending 9 days now. Thanks

**Comment by alexellis** [comment]
@Gadgetoid @AndiCui Hi chaps,

I have submitted a backwards compatible change which will allow for unit testing and working off device - i.e. on a PC. I hope this is useful for you. I've tested it against the examples in the current master and found everything to be working. 

If you are good to merge this request then I will start to add some tests for the relatively obscure buffer manipulations etc.

Thanks,

Alex

**Refactor a pythonic class from the static module**
- Enables unit testing
- Enables development on PC away from i2c bus by swapping dependency out

- Interface is honoured and examples were tested
- Unit tests folder to follow

**Comment by AndiCui** [comment]
Going to test your stuff soon (aka tonight.) (I don’t have write permission. But i will spam @Gadgetoid for you)

**Comment by AndiCui** [comment]
@alexellis I did some basic test on your lib. Plz use import .controller if you want to import stuff from the file. (python3 stuffs). Other than that, i think it may more sense if you rename the controller.py to scrollphat.py or IS31FL3730.py. (Just my personal idea)

The ip example relies on netifaces, which is NOT preinstalled (on jessie lite).

**Comment by alexellis** [comment]
@AndiCui I can drop netifaces - do you have an alternative for internal IP I could replace it with? 

As for the name 'controller' I was thinking [LED] controller, but I wasn't completely committed to the choice then scrollphat felt too recursive. As another idea.. how about MatrixDriver as it's called in the spec sheet? http://www.issi.com/WW/pdf/31FL3730.pdf

**Comment by AndiCui** [comment]
@alexellis bash ifconfig?

by scrollphat i meant the hardware :), it is way too recursive. I think IS31FL3730 make a bit more sense‽  ( @Gadgetoid )

**Comment by Gadgetoid** [comment]
In keeping with some of our other base library names, I'd be inclined to agree with `IS31FL3730`, even if it sounds cryptic and garbage to most users. In fact it would probably be sensible to maintain and distribute this as a separate library which users can leverage for their own projects on the Pi. Especially since this driver IC supports things like 8x8 matrixes also.

Examples:

* https://github.com/pimoroni/sn3218
* https://github.com/pimoroni/st7036
* https://github.com/pimoroni/cap1xxx

I'm really in favour of doing this, since it opens up these libraries for wider use. The extra dependency and complexity introduced into the library is handled well by pip.

**Comment by alexellis** [comment]
The hard-coded 5 and 11 magic numbers have been catching my eye - they need moving into variables, and they can also be put through the constructor leaving a default in the old static module initialiser. 

I will test the rename of controller to IS31FL3730 and push that.

**Comment by alexellis** [comment]
@Gadgetoid OK - following the base hardware identifier is similar to what Adafruit do in their repository, so it would also be consistent for people using python libraries for hardware. Change has been pushed to my fork.

**Comment by AndiCui** [comment]
@alexellis I am a bit turned off by the name `IS31FL3730_1`. `controller` makes more sense here to me.

**Comment by alexellis** [comment]
@AndiCui Done.

**Comment by AndiCui** [comment]
Thx:) @Gadgetoid

**Comment by stuphi** [comment]
Ok, I have just just tried this and the sine.py example does not work now. Everything else seems fine.

**Comment by alexellis** [comment]
@stuphi my bad on that one, thanks for picking it up. That example was doing something a bit hack-y by editing the buffer directly. I've fixed it and retested OK for me.

**Comment by AndiCui** [comment]
@alexellis the sine example and the ip example doesn't work on me.
It seems that the code have problems dealing with buffer.
Plz check buffer_len() and set_buffer()


Test env: A+ , Jessie lite

**Comment by alexellis** [comment]
@AndiCui The reason sine.py was broken was that unlike the other examples it directly replaced the internal buffer object. As soon as I added set_buffer to replicate the functionality it started working again at my end. I've just done an `rm -rf` and a fresh clone from my fork - which gave me the expected sine pattern.

If you have absolutely no local merge conflicts then sine.py should look like:

```
#!/usr/bin/env python

import scrollphat
import math
import time
import sys

i = 0
buf = [0] * 11
scrollphat.set_brightness(20)

while True:
    try:
        for x in range(0, 11):
            y = (math.sin((i + (x * 10)) / 10.0) + 1) # Produces range from 0 to 2
            y *= 2.5 # Scale to 0 to 5
            buf[x] = 1 << int(y)

        scrollphat.set_buffer(buf)
        scrollphat.update()

        time.sleep(0.005)

        i += 1
    except KeyboardInterrupt:
        scrollphat.clear()
        sys.exit(-1)
```

It's a bit late now, but let me know if everything is clean etc on your clone of my fork.

**Comment by AndiCui** [comment]
@alexellis Merge Conflict... Stupid me.

**Comment by AndiCui** [comment]
@Gadgetoid This pull req. is already 15 days old. Merge?

**Comment by alexellis** [comment]
@Gadgetoid  +1 to this

**Comment by Gadgetoid** [comment]
Merged! I did actually take the time to grab and test this. Nice work!

**Comment by AndiCui** [comment]
@Gadgetoid I think this edit deserve a version number. :)
Good work @alexellis !

**Comment by alexellis** [comment]
We got there in the end.. version bump sounds good :) Challenge for @AndiCui if you have time, to add a couple of unit tests

**Comment by AndiCui** [comment]
@alexellis I have no idea what can be tested without a test rig (basically one or two mounted LDR).
////////
@Gadgetoid : plz tell us your idea on version bump

**Comment by alexellis** [comment]
@AndiCui I've just added some more unit test coverage and pushed it to my own fork, take a look. There is quite a lot of code uncovered, so if you fancy it, do add some more tests. These do not test the device itself, but the library we just extracted in this pull request  - i.e. its buffer manipulation and interaction with i2c.

https://github.com/alexellis/scroll-phat/commit/14a66a86a7d8fcb2cca92936aad0a972fba22c1f

**Pull request merged**
