### PR TITLE
Add ability to invert display. Change INVERT to True at top of scroll…

### PR DESCRIPTION
**Pull request by stuphi**
…phat.py

### CODE REVIEW

**Comment by alexellis** [comment]
@Gadgetoid  @stuphi  Functionally tested with uptime.py simple-text-scroll.py and progress.py. Worked really well.

**Comment by stuphi** [comment]
Converting numbers to strings and back seems a little dirty. There is probably much better ways than this, but I have had a go here: https://github.com/stuphi/scroll-phat/blob/inverted2/library/scrollphat.py
If this method is preferred, I can create a new pull request.

**Comment by alexellis** [comment]
I'm just like yourself... interested in playing with the scrollPhat and seeing if I can contribute a little bit. @Gadgetoid has done a grand job with his library - keeping it so concise.

To me, the code is easier to read with this approach. How were you going to set INVERT from an example? Is that bit still missing? I.e. scrollphat.set_inverted(True / False ) (even.. flip_display() ?)

I'm also having a stab at a Node.js library, which you are welcome to take a look at if that's your thing.

**Comment by stuphi** [comment]
To be honest, I don't know the best way to switch. However, I did think that if people use this in a project, it will either be one way or the other, and not likely to switch once set, so the need for a function is not so high.

I also started an alternative version, but in Go.

**Comment by Gadgetoid** [comment]
@stuphi's version seems a little more sane. While using Python's more esoteric features to create one-liners is good for saving code space, it doesn't bode well for readability.

Off the top of my head I can't think of a more elegant way to invert bits. For sanity we should probably also name this feature "rotate" since that's what it does, and inverting bits would traditionally mean:

`0b00000001` to `0b11111110`

Which is an entirely separate, and also possibly desirable feature in itself.

It should ideally also be switchable from outside of the library file since it's a pain to even find, much less edit, if it's installed. If this were installed as a library then the following should be possible:

```
import scrollphat
scrollphat.rotate = True
```

**Comment by stuphi** [comment]
Thanks for the input. I have created a new pull request from my alternative branch that address' this.
https://github.com/pimoroni/scroll-phat/pull/21

**Pull request closed without merging**
