### PR TITLE
Countdown Timer Example

### PR DESCRIPTION
**Pull request by AndiCui**
@alexellis @Gadgetoid 
Inspired by clock example by @pauljrowland https://github.com/pimoroni/scroll-phat/pull/40

### CODE REVIEW

**Comment by alexellis** [comment]
@AndiCui 

Quick spell-check: * intergers = integers

`while 1` may eat a lot of CPU, could you put a small time.sleep() in there between iterations?

**Comment by AndiCui** [comment]
@alexellis I am doing the delays after in if and elif. I delay different amount of time for different level.

**Comment by AndiCui** [comment]
Does someone have any remarks on this?

**Comment by alexellis** [comment]
Having a look now, but it might be worth validating against dates entered in the past - and time entry would be more natural with:

Enter time (hh:mm): 
22:27

**Comment by alexellis** [comment]
Hi @AndiCui ...  testing the example... I just get a blank screen when I entered:

```
Please enter the target time with integers
Year:	2016
Month:	03
Date:	18
Hour:	22
Minute:	30
```

Same again with:

```
Year:	2016
Month:	3 
Date:	17
Hour:	22
Minute:	40
```

**Comment by Gadgetoid** [comment]
I noticed that this flickered quite intensely when it was running. This is because `scrollphat.clear` triggers an update, rather than emptying the buffer ready for fresh content.

I've added `scrollphat.clear_buffer` in https://github.com/pimoroni/scroll-phat/commit/dbd18ac54b2674bdab8250b020936840dc3988fa to address cases like this.

You should drop `scrollphat.clear` from lines 24, 29 and 34 and add `scrollphat.clear_buffer()` somewhere around line 19. This will greatly reduce eye pain!

**Comment by AndiCui** [comment]
@alexellis going to troubleshoot when i have time. 
I agree that date and time are more comfortable with other ways of entry.
here is my list of questions:
- how do I provide a default answer (it is 100% sure that the user will enter 2016)
- how to interpret HH:MM with a clean way

**Comment by AndiCui** [comment]
@alexellis I cannot reproduce the your bug. Flickering is driving my crazy. Changing for  `scrollphat.clear_buffer` @Gadgetoid

**Comment by alexellis** [comment]
So the other way to do this (and I think maybe easier.. ) is to take in a string on the command line, i.e:

```
sudo python countdown.py 2016-03-17 22:00
```

When reading every variable in on a prompt it means you have to start again if you enter something wrong. You also have to validate every string before parsing them individually. 

In terms of parsing HH:MM, you can use [strptime](https://docs.python.org/2/library/time.html#time.strptime) which I found by typing into Google "parse python date time" - there is really a lot you can find out by using a search engine or by looking into the python docs. I find it really helpful myself.

```
$ python
>>> time.strptime("2016-03-17 22:30", "%Y-%m-%d %H:%S")
time.struct_time(tm_year=2016, tm_mon=3, tm_mday=17, tm_hour=22, tm_min=0, tm_sec=30, tm_wday=3, tm_yday=77, tm_isdst=-1)
>>> 
```

Does that answer the question?

**Comment by AndiCui** [comment]
@alexellis please allow my to faceplam...... I am thinking the whole time for some string manipulation

**Comment by AndiCui** [comment]
@alexellis Should I use YYYYMMDD as date formate or the hyphenated YYYY-MM-DD

**Comment by Gadgetoid** [comment]
https://en.wikipedia.org/wiki/ISO_8601

EG: 2016-03-16T21:47:19

You should look into Python's argparse: https://docs.python.org/3/library/argparse.html#module-argparse

And validation: https://stackoverflow.com/questions/25470844/specify-format-for-input-arguments-argparse-python

So you can perhaps support:

```
python countdown.py --to-date 2016-03-17 22:00
```

or:

```
python countdown.py --seconds 1932
```

**Comment by alexellis** [comment]
I'd recommend you use the format I typed up in the example. It's a fairly common one and the hyphens help split up the screen. So perhaps you can do it all through sys.argv instead of through individual prompts.

```
$ cat andy1.py 
import time
import sys

print(sys.arg)

$ sudo python andy1.py hi this is an example
['andy1.py', 'hi', 'this', 'is', 'an', 'example']
```

Full example:

```
$ cat andy2.py 
import time
import sys

dateVal = sys.argv[1]
timeVal = sys.argv[2]

parsed = time.strptime(dateVal + " " + timeVal, "%Y-%m-%d %H:%S")

print(parsed)
```

Running it:

```
sudo python andy2.py 2016-03-17 22:30
time.struct_time(tm_year=2016, tm_mon=3, tm_mday=17, tm_hour=22, tm_min=0, tm_sec=30, tm_wday=3, tm_yday=77, tm_isdst=-1)
```

Good luck... don't rush it :+1:

**Comment by AndiCui** [comment]
@alexellis @Gadgetoid thx for the tips. Those stuff are the dark areas of my understanding of python (which is built from trails and errors). It may take so time

**Comment by Gadgetoid** [comment]
@AndiCui any excuse to coax you into learning moar Python ;)

It would be nice to have more examples with slightly more advanced stuff in, but it's always a delicate balance of advanced vs clear and educational.

SPOILER:
---

For the record, the idea of parsing a date on the command line interested me a little too much. Here's what I've got so far:

```python
import argparse
import datetime

def valid_datetime(dt):
    for fmt in ('%Y-%m-%dT%H:%M', '%Y-%m-%dT%H:%M:%S',
                '%Y-%m-%d %H:%M', '%Y-%m-%d %H:%M:%S'):
        try:
            return datetime.datetime.strptime(dt, fmt)
        except ValueError:
            pass
    raise argparse.ArgumentTypeError("Invalid date: '{0}'.".format(dt))

def valid_time(t):
    d = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%dT')
    return valid_datetime(d + t)

parser = argparse.ArgumentParser(description="Countdown to a specific date, or for a number of seconds.")
parser.add_argument('--to-date', type=valid_datetime, help="Countdown date - format YYYY-MM-DDTHH:MM(:SS)")
parser.add_argument('--to-time', type=valid_time, help="Countdown time - formath HH:MM(:SS)")
args = parser.parse_args()

print(args)
```

**Comment by AndiCui** [comment]
I am also considering adding a timer function. It counts the rest of a time span (for programmers: it counts to a point of time, which is calculated from the span). I am going to spread the work out from now though the upcoming week.

**Comment by Gadgetoid** [comment]
It's probably a good idea to ignore my suggestions... they got out of hand pretty quickly:

https://gist.github.com/Gadgetoid/b771131b1adb624b4753

**Comment by alexellis** [comment]
It's hard to hold back on the cool features when you know about the goodness of argsparser, classes, methods etc.. but in the spirit of 'K.I.S.S'  (keep it simple)... 

```
import time
import sys

def parse_args():
    if(len(sys.argv) == 1):
        return None

    dateVal = sys.argv[1]
    timeVal = sys.argv[2]

    parsed_date = None
    try: 
        parsed_date = time.strptime(dateVal + " " + timeVal, "%Y-%m-%d %H:%M")
    except:
        return None
    return parsed_date

parsed_date = parse_args()

if(parsed_date is None):
    print("Please enter a date in this format: yyyy-mm-dd hh:mm")
    sys.exit(-1)

count_down_to(parsed_date)
```

@AndiCui 

Learning roar Python would give you a wider set of options for solving coding problems like this count-down timer... And obviously it doesn't have to be only through contributing scrollphat examples. Have you tried GPIO Zero yet for controlling LEDs/sensors etc? I combined the scrollphat with a PIR sensor and some networking over at https://github.com/alexellis/rpi-display/

**Comment by AndiCui** [comment]
My time interpretation code doesn’t work somehow, can somebody find the bug? Thx
`
#!/usr/bin/env python

import datetime
import argparse

parser = argparse.ArgumentParser(description='Countdown and display reamining time on the scroll phat.')

def ValidateTargetInput(target):
    AcceptedFormat = ('%Y-%m-%dT%H:%M:%S', '%Y-%m-%dT%H:%M', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%H:%M:%S', '%H:%M')
    for f in AcceptedFormat:
        try:
            return datetime.datetime.strptime(target, f)
        except ValueError:
            pass
    raise argparse.ArgumentTypeError("Invalid date")

parser.add_argument('--target', metavar="[YYYY-MM-DD] HH:MM:[SS]", type=ValidateTargetInput, help='Display the remaining time to a target moment')
#parser.add_argument('--timer', metavar="HH:MM:SS", help='Display the remaining time till entered time span runs up')
args = parser.parse_args()

print (args)
`

**Comment by AndiCui** [comment]
Should I say that i sadly gave up on this. Sry for the delays. I think that’s still maybe interesting for Mr. @alexellis to finish this case. Then I will learn by #RTFC

**Comment by alexellis** [comment]
@AndiCui I'm sure you still learnt a lot during the process. If you fancy trying something slightly different I'm looking for contributions to a little coding task PI-related. http://blog.alexellis.io/april-1st-node-js-vs-bash/ I'm trying to coax some Ruby or Python out of @Gadgetoid for it ;-)

**Pull request closed without merging**
