### PR TITLE
Add bbcweather.py scrolling 3-day forecast for your postal area

### PR DESCRIPTION
**Pull request by campag**
Usage: ./bbcweather SW19
for a Wimbledon postal area forecast.

Hacked out of your uptime.py example.

Defaults to Sheffield-on-Sea if no single postal area code is supplied as command-line argument.

### CODE REVIEW

**Comment by AndiCui** [comment]
Nice work. I think to rename it to ukweather or something might make more sense (?)
I don't know which weather info supplyer provide international data without cuttering and spaghetti-ing the whole thing.

**Comment by campag** [comment]
Agreed, ukweather is more descriptive.

An international version would be perfect, when I have a spare moment...

**Comment by Gadgetoid** [comment]
Really nice work! I'll merge and then rename it as suggested!

**Comment by alexellis** [comment]
@campag  @Gadgetoid I didn't get a chance to mention before - but feedparser may not be shipped with Rasbpian, so could be an extra piece of software to install. May be worth mentioning in a comment in the top of the file. When testing I got:

```
Traceback (most recent call last):
  File "ukweather.py", line 3, in <module>
    import feedparser
ImportError: No module named feedparser
```

Good work btw.

**Pull request merged**
