### PR TITLE
Little http server that makes the scrollphat examples

### PR DESCRIPTION
**Pull request by joosteto**
Hi @Gadgetoid ,

Here's a http server that makes the scrollphat examples
accessable over the web, and adds adjustable brightness,
update time and rotation for some of them.

Tested with IPv4 and IPv6, running on either python 2.7 and 3.4

### CODE REVIEW

**Comment by alexellis** [comment]
As cool as it is to launch the Python scripts through a low-level HTTP server, something like Flask would probably be more usable and concise https://github.com/alexellis/pyPlaylist/blob/master/app.py I know that a lot of the examples so far were added to show how to interact with the screen or how to learn basic elements of Python.

With the sine, cpu, scrolltext etc examples being duplicated - who will dual-maintain the files? And if someone adds a new example, do they now also need to update the HTTP server?

It's a fun idea and I think it would be great in its own repo - I did the same thing when I wrote some code with Redis to create a remote sensor display https://github.com/alexellis/rpi-display/

**Comment by Gadgetoid** [comment]
This is a great little example, but as @alexellis rightfully points out it's perhaps a little complicated and bakes too much duplicate functionality into its workings.

I guess we have some possible options:

* Modify the rogue examples to work with this example and make sure all future examples match the same pattern.

* Evolve this example into something a little more generalized and standalone. An API for displaying text on Scroll pHAT perhaps? Or something bonkers like Unicorn Paint: http://learn.pimoroni.com/tutorial/unicorn-hat/getting-started-with-unicorn-paint


Apart from the obvious rudeness of "Hey, great example, could you make it do this totally different thing 'cos that would be awesome" I very much favour the latter :D

**Comment by joosteto** [comment]
About dual-maintaining: If the webserver gets added, I was about to propose to rewrite the scrolltext & sine files, so that they can be import-ed by the webserv module, and called from there (like is done now with life.py).
Ah, I see that's what @Gadgetoid suggests too, as option 1. So, yes, I'm fine with that, if that's what you want, I'll generate a patch that updates those examples and webserv.

**Comment by alexellis** [comment]
@joosteto  I think we are going to make the barrier to contributing quite high if we create base classes etc... You've got a good idea, do you see any issues with starting your own Github repo for the project? (option 2)

**Pull request closed without merging**
